from enum import Enum

class EnumLoginOpCode(Enum):
    ACCEPT_TOS = 0x7
    AFTER_LOGIN = 0x9
    SERVERLIST_REREQUEST = 0x4
    CHARLIST_REQUEST = 0x5
    CHAR_SELECT = 0x13
    LOGIN_PASSWORD = 0x1
    RELOG = 0x1C
    SERVERLIST_REQUEST = 0xB
    SERVERSTATUS_REQUEST = 0x6
    CHECK_CHAR_NAME = 0x15
    CREATE_CHAR = 0x16
    DELETE_CHAR = 0x17
    VIEW_ALL_CHAR = 0x0D
    PICK_ALL_CHAR = 0x0E
    REGISTER_PIN = 0x0A
    GUEST_LOGIN = 0x2
    REGISTER_PIC = 0x1D
    CHAR_SELECT_WITH_PIC = 0x1E
    SET_GENDER = 0x08
    VIEW_ALL_WITH_PIC = 0x20
    VIEW_ALL_PIC_REGISTER = 0x1F